Make StateMachineCtap2 respect runloop cancellations
mozilla/authenticator-rs pull request #228
Opened 2023-02-23 05:26 UTC by jschanck

Resolves #227

2023-02-23 23:33 UTC, mozkeeler approved these changes
LGTM!

2023-02-24 06:33 UTC, msirringhaus requested changes
Some minor things

2023-03-01 06:19 UTC, jschanck commented on src/transport/hid.rs
> +            self.u2f_write(u8::from(HIDCmd::Cancel), &[])?;
The read is not necessary but it gives us a sensible return value in both cases.

It looks like `HIDDevice::cancel()` is only used in `DeviceSelector::cancel_all` right now. I don't think its use there is entirely correct, as it doesn't really make sense to (only) send the `CTAPHID_CANCEL` message when we might have U2F devices connected.

In fact, if I plug in a U2F-only device alongside a CTAP2-capable device and select the CTAP2 device, the U2F device continues to blink. So I think `HIDDevice::cancel()` needs to do more than send `CTAPHID_CANCEL`. If so I shouldn't use it in `HIDDevice::sendrecv()`. It should also probably be renamed.

2023-03-01 08:13 UTC, msirringhaus commented on src/transport/hid.rs
> +            self.u2f_write(u8::from(HIDCmd::Cancel), &[])?;
The problem is: I don't know of a way to cancel an ongoing U2F-request. `CTAPHID_CANCEL` was introduced in ctap2.0. U2F only seems to have: 

> [4.1.1 U2FHID_MSG](https://fidoalliance.org/specs/fido-u2f-v1.2-ps-20170411/fido-u2f-hid-protocol-v1.2-ps-20170411.html#u2fhid_msg)
>    [4.1.2 U2FHID_INIT](https://fidoalliance.org/specs/fido-u2f-v1.2-ps-20170411/fido-u2f-hid-protocol-v1.2-ps-20170411.html#u2fhid_init)
>    [4.1.3 U2FHID_PING](https://fidoalliance.org/specs/fido-u2f-v1.2-ps-20170411/fido-u2f-hid-protocol-v1.2-ps-20170411.html#u2fhid_ping)
>    [4.1.4 U2FHID_ERROR](https://fidoalliance.org/specs/fido-u2f-v1.2-ps-20170411/fido-u2f-hid-protocol-v1.2-ps-20170411.html#u2fhid_error)
> 
> 4.2 Optional commands
> 
>    [4.2.1 U2FHID_WINK](https://fidoalliance.org/specs/fido-u2f-v1.2-ps-20170411/fido-u2f-hid-protocol-v1.2-ps-20170411.html#u2fhid_wink)
>    [4.2.2 U2FHID_LOCK](https://fidoalliance.org/specs/fido-u2f-v1.2-ps-20170411/fido-u2f-hid-protocol-v1.2-ps-20170411.html#u2fhid_lock)

Thats why currently, we let them blink and run into the timeout at some point. It's not ideal, but I don't know of any other way right now.

2023-03-01 11:32 UTC, msirringhaus commented on src/transport/hid.rs
> +            self.u2f_write(u8::from(HIDCmd::Cancel), &[])?;
Ok, actually U2F operations are non-blocking. That means, we can just basically send "whatever" to the token to make it stop, like WINK or PING. 
I tried to figure out what Chromium is doing, but couldn't. The Cancel-function says, this only works with CTAP2 devices and is a no-op for CTAP1 devs. I _think_ they are implicitly sending a WINK command.

2023-03-01 18:37 UTC, jschanck commented on src/transport/hid.rs
> +            self.u2f_write(u8::from(HIDCmd::Cancel), &[])?;
We don't need to send anything to CTAP1 devices. But we do need to exit out of the loop in `send_ctap1_cancellable` when the device selector calls `cancel_all`. The existing `HIDDevice::cancel` function won't work for that. I'll update the patch.

2023-03-01 18:51 UTC, jschanck commented on src/transport/hid.rs
> +            self.u2f_write(u8::from(HIDCmd::Cancel), &[])?;
With the new version, an unselected CTAP1 device blinks 3 or 4 times after `DeviceSelector::cancel_all` is sent but then it stops blinking. I'm not sure whether we can do better, maybe the hardware just blinks a few times after any activity?

2023-03-07 18:40 UTC, jschanck commented
Requesting review for the second patch. thanks!

2023-03-07 18:45 UTC, mozkeeler approved these changes
LGTM!

2023-03-07 18:49 UTC, merged